Allow libraries to not exist

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -130,11 +130,13 @@ jobs:
                       echo "Failed to match sha512 for $MACPORTS_CACHE"
                       exit 1
                   fi
-                  tar xj -C "$OPENSCAD_LIBRARIES" -f /tmp/libraries.tar.bz2 || true
-                  if [ "$(shasum -a 512 /tmp/$LIBRARIES_CACHE | cut -d ' ' -f 1)" != "$LIBRARIES_CACHE_SHA512" ]; then
-                      echo "Failed to match sha512 for $LIBRARIES_CACHE"
-                      exit 1
-                  fi
+                  if [ -f /tmp/libraries.tar.bz2 ]; then
+                      tar xj -C "$OPENSCAD_LIBRARIES" -f /tmp/libraries.tar.bz2 || true
+                      if [ "$(shasum -a 512 /tmp/$LIBRARIES_CACHE | cut -d ' ' -f 1)" != "$LIBRARIES_CACHE_SHA512" ]; then
+                          echo "Failed to match sha512 for $LIBRARIES_CACHE"
+                          exit 1
+                      fi
+                  fi    
                   export PKG_CONFIG_PATH=$OPENSCAD_LIBRARIES/lib/pkgconfig
                   export DYLD_LIBRARY_PATH=$OPENSCAD_LIBRARIES/lib
                   export DYLD_FRAMEWORK_PATH=$OPENSCAD_LIBRARIES/lib
